# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44a9c37c73d3ccfac9d41cdb2cfdec11a35707a99e5b41e229e0918d5e01617a71de5cc752b884f193ea09cf870fcb69ceaf98972cbe37089dffc1dce61706df

test:
  secret_key_base: 19b58b1e78cebcc89ed0f2a950bf577b74bf87b47b123c8045f4ed26417a48ad99fb9ceff4e4b022fa09cc74dfe3115900eb13dbd879bc15ea07c41ac5016576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
